[package]
name = "bevy-chess"
version = "0.1.0"
authors = ["Saeed <s4eed@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
bevy_mod_picking = "0.3.1"